from datetime import datetime, timezone
from pathlib import Path

from jkb.models.entry import NormalizedEntry
from jkb.models.dayone import DayOneLocation, DayOnePhoto
from jkb.stages.validate import ValidationResult, ValidationWarning
from jkb.utils.migration_log import MigrationLog


def _entry(uuid: str = "UUID1", journal: str = "Test", **kwargs) -> NormalizedEntry:
    defaults = dict(
        uuid=uuid,
        journal=journal,
        creation_date=datetime(2020, 1, 1, tzinfo=timezone.utc),
    )
    defaults.update(kwargs)
    return NormalizedEntry(**defaults)


def _result(uuid: str = "UUID1", journal: str = "Test", **kwargs) -> ValidationResult:
    defaults = dict(uuid=uuid, journal=journal)
    defaults.update(kwargs)
    return ValidationResult(**defaults)


def test_counts_written(tmp_path):
    log = MigrationLog()
    e = _entry()
    r = _result()
    log.record(e, r, tmp_path / "file.md")
    log.record(e, r, None)
    assert log._total_attempted == 2
    assert log._total_written == 1
    assert log._total_skipped == 1


def test_warning_counted(tmp_path):
    log = MigrationLog()
    e = _entry()
    r = _result(warnings=[ValidationWarning.MISSING_TEXT])
    log.record(e, r, None)
    assert log._warning_counts["missing_text"] == 1
    assert log._total_warned == 1


def test_missing_attachment_recorded(tmp_path):
    log = MigrationLog()
    e = _entry()
    r = _result(warnings=[ValidationWarning.MISSING_ATTACHMENT], missing_attachment_ids=["PHOTO1"])
    log.record(e, r, None)
    assert len(log._missing_attachments) == 1
    assert log._missing_attachments[0]["attachment_id"] == "PHOTO1"


def test_invalid_entry_recorded(tmp_path):
    log = MigrationLog()
    e = _entry(uuid="DUP1", journal="JournalA")
    r = _result(uuid="DUP1", journal="JournalA", is_valid=False, warnings=[ValidationWarning.DUPLICATE_UUID], duplicate_of_journal="JournalB")
    log.record(e, r, None)
    assert len(log._invalid_entries) == 1
    assert "JournalB" in log._invalid_entries[0]["reason"]


def test_coverage_counted(tmp_path):
    log = MigrationLog()
    loc = DayOneLocation(latitude=14.5, longitude=121.0)
    e = _entry(location=loc, tags=["travel"])
    r = _result()
    log.record(e, r, tmp_path / "f.md")
    assert log._has_location == 1
    assert log._has_tags == 1
    assert log._has_weather == 0


def test_write_produces_markdown(tmp_path):
    log = MigrationLog()
    e = _entry()
    r = _result()
    log.record(e, r, tmp_path / "file.md")
    out = tmp_path / "migration-log.md"
    log.write(out)
    content = out.read_text(encoding="utf-8")
    assert "# Migration Log" in content
    assert "## Summary" in content
    assert "## Warnings Breakdown" in content
    assert "## Metadata Coverage" in content
    assert "## Missing Attachments" in content
    assert "## Invalid / Skipped Entries" in content
    assert "*Generated by jkb migrate*" in content


def test_write_counts_correct(tmp_path):
    log = MigrationLog()
    for i in range(3):
        log.record(_entry(uuid=f"U{i}"), _result(uuid=f"U{i}"), tmp_path / f"f{i}.md")
    log.record(_entry(uuid="U3"), _result(uuid="U3"), None)
    out = tmp_path / "log.md"
    log.write(out)
    content = out.read_text()
    assert "| Total attempted | 4 |" in content
    assert "| Successfully written | 3 |" in content
